services:
  # NestJS BFF
  app:
    build: .
    container_name: gesture-bff
    restart: unless-stopped
    env_file: .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - gesture-net

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8081:8080"

networks:
  gesture-net:
    external: true
