name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]
    # branches: [ "production" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST_IP }} >> ~/.ssh/known_hosts

    - name: Deploy Service
      run: |
        ssh ${{ secrets.EC2_HOST_ID_ROOT }}@${{ secrets.EC2_HOST_IP }} << 'EOF'
          set -e
          rm -rf ~/nestjs-application && mkdir ~/nestjs-application
          cd ~/nestjs-application
          git clone -b main https://github.com/3-1-ChoiInSawMan/gesture_NestJS_Backend .
          docker rm -f gesture-bff || true
          docker build -t gesture-bff .
          docker run --name gesture-bff \
          -e "NODE_ENV=${{ vars.NODE_ENV }}" \
          -e "SECURITY_PUBLIC_KEY=${{ secrets.SECURITY_PUBLIC_KEY }}" \
          -e "SECURITY_CORS_ORIGIN=${{ vars.SECURITY_CORS_ORIGIN }}" \
          -e "SPRING_SERVER_URL=${{ vars.SPRING_SERVER_URL }}" \
          -e "SERVER_PORT=${{ vars.SERVER_PORT }}" \
          --restart unless-stopped \
          -d -p "${{ vars.SERVER_PORT }}:${{ vars.SERVER_PORT }}" \
          gesture-bff
        EOF

    - name: Check Service Health
      run: |
        ssh -T -o LogLevel=ERROR ${{ secrets.EC2_HOST_ID_ROOT }}@${{ secrets.EC2_HOST_IP }} <<'EOF'
          for attempt in 1 2 3 4 5; do
            if curl -fsS "http://localhost:${{ vars.SERVER_PORT }}/api/v1" > /dev/null; then
              echo "attempt $attempt success. BFF is healthy."
              exit 0
            fi
            echo "attempt $attempt failed. retrying..."
            sleep 3
          done

          echo "=== docker ps ==="
          docker ps -a | grep gesture-bff || true
          echo "=== docker logs ==="
          docker logs gesture-bff || true
          exit 1
        EOF
