name: Deploy to Amazon EC2

on:
  push:
    branches: [ "production" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST_IP }} >> ~/.ssh/known_hosts

    - name: Deploy Service
      run: |
        ssh ${{ secrets.EC2_HOST_ID_ROOT }}@${{ secrets.EC2_HOST_IP }} << 'EOF'
          rm -rf ~/nestjs-application && mkdir ~/nestjs-application
          cd ~/nestjs-application
          git clone -b production https://github.com/3-1-ChoiInSawMan/gesture_NestJS_Backend .
          docker rm -f gesture-bff
          docker build -t gesture-bff .
          docker run --name gesture-bff \
          -e "SECURITY_PUBLIC_KEY=${{ secrets.SECURITY_PUBLIC_KEY }}" \
          -e "SECURITY_CORS_ORIGIN=${{ vars.SECURITY_CORS_ORIGIN }}" \
          -e "SPRING_SERVER_URL=${{ vars.SPRING_SERVER_URL }}" \
          -e "SERVER_PORT=${{ vars.SERVER_PORT }}" \
          -d -p "${{ vars.SERVER_PORT }}:$${{ vars.SERVER_PORT }}/